app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('dqapp.urls')),
    path('accounts/',include('accounts.urls')),
    path('dqcharts/',include('dqcharts.urls')),
    path('admin/', admin.site.urls),
]

app/dqapp/forms.py
from django import forms
from . models import Sourcedb, Connectiondetails, Connections, Dqcheck
from django.forms import ModelForm


class NewconnectionFormMysql(forms.Form):
    # dblist = []
    # Choices = Sourcedb.objects.all()
    # for Choice in Choices:
    #     tup=(Choice.id,Choice.dbname)
    #     dblist.append(tup)
    
    #sourcedb = forms.ChoiceField(choices=dblist,label='Select Source Database ',initial='')
    #sourcedb = forms.ModelChoiceField(required=True, widget=forms.Select, queryset=Sourcedb.objects.all())
    dbname = forms.CharField(label='Enter database name         ')
    schemaname = forms.CharField(label='Enter schema name       ')
    username = forms.CharField(label='Enter user name           ')
    password = forms.CharField(label='Enter password            ',widget=forms.PasswordInput)
    hostname = forms.CharField(label='Enter database hostname   ')
    port = forms.CharField(label='Enter database port           ')
    sid = forms.CharField(label='Enter database sid             ',required=False)
    connectionname = forms.CharField(label='Connection name to save')

class NewconnectionFormOracle(forms.Form):

    schemaname = forms.CharField(label='Enter schema name')
    username = forms.CharField(label='Enter user name')
    password = forms.CharField(label='Enter password ',widget=forms.PasswordInput)
    hostname = forms.CharField(label='Enter database hostname')
    port = forms.CharField(label='Enter database port')
    #sid = forms.CharField(label='Enter database sid',required=False)
    connectionname = forms.CharField(label='Connection name to save')

class NewconnectionFormPostgres(forms.Form):

    schemaname     = forms.CharField(label='Enter schema name')
    username       = forms.CharField(label='Enter user name  ')
    password       = forms.CharField(label='Enter password   ',widget=forms.PasswordInput)
    hostname       = forms.CharField(label='Enter database hostname')
    port           = forms.CharField(label='Enter database port')
    connectionname = forms.CharField(label='Connection name to save')

class NewdqcheckForm(forms.Form):
    
    connectionlist = [(0,'--------')]
    Choices = Connections.objects.all()
    for choice in Choices:
        tup = (choice.id,choice.connectionname)
        connectionlist.append(tup)
    
    connections = forms.ChoiceField(choices=connectionlist,label='Select Database Connection ')

class RundqcheckForm(forms.Form):
    dqchecklist = [(0,'--------')]
    Choices = Dqcheck.objects.all()

    for choice in Choices:
        tup = (choice.id,choice.dqcheckname)
        dqchecklist.append(tup)

    dqcheckname = forms.ChoiceField(choices=dqchecklist,label='Select Check ')
    


    
    

app/templates/adddqcheck.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
    <form action="adddqcheck" method="POST" id="dqcheckform" data-tables-url="{% url 'loadtables' %}" novalidate enctype="multipart/form-data">
        {% csrf_token %}

        <h1> Rules Configuration</h1>
        <!-- {{ form.as_p }} -->
        <label for="dqcheckname">Enter Name For This Check : </label>
        <input type="text" name="dqcheckname" id="dqcheckname">

        <br><br>

        <label for="id_connections">Select Database Connection :</label>

        <select id="id_connections" name="id_connections"  required>
            <option value="" disabled="true" selected>-- Select --</option>
            {% for connection in connectionlist %}
            <option value="{{ connection.id }}">{{ connection.connectionname }}</option>
            {% endfor %}
        </select>

        <br><br>

       
        <label for="tables">Select Table :</label>
        
        <select name="tables"  id="tables" data-colrule-url="{% url 'loadcolumnNrules' %}" novalidate>
            <option value="" disabled="true" selected>-- Select --</option>     
        </select>
        <button type="button" name="qprofile" id="qprofile" disabled="true">Quick Profile</button>

                <br><br>
        
             
            <table id="columntable">
            
                    <tr>
                        <td colspan="1">Select Column</td>
                        <td colspan="1">Select Quality Check</td>
                        <td colspan="1">Provide Test Values</td>
                        <td><button type="button" id="addrow"></button></td>
                        
                    </tr>
                
                
                    <tr id="tablerow">  
                                         
                    </tr>
                
                
            </table>

        <br><br>

        <input type="submit" value="Save DQ Check">

        <br><br>
        
        {% for message in messages %}
        <div class="message">
        {{ message }}
        </div>
        {% endfor %}
        
    </form>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_connections").change(function () {
        var url = $("#dqcheckform").attr("data-tables-url");  // get the url of the `loadtables` view
        var connectionId = $(this).val();  // get the selected connection id from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/ajax/loadtables/)
            data: {
            'connectionid': connectionId       // add the connection id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `loadtables` view function
                console.log(data);
            $("#tables").html(data);  // replace the contents of the table input with the data that came from the server
            }
        });

        });

        $(document).ready(function(){
            $(document).on('click','#addrow', function(){
                var htmlappend = '';
                var url = $("#tables").attr("data-colrule-url");  // get the url of the `loadcolumnNrules` view
                var connectionId = $("#id_connections").val();  // get the selected connection ID from the HTML input
                var tablename = $("#tables").val(); // get the selected table from the HTML input
         
                 $.ajax({                       // initialize an AJAX request
                     url: url,                    // set the url of the request (= localhost:8000/ajax/loadcolumnNrules/)
                     data: {
                     'connectionid': connectionId, // add the connectioned id to the GET parameters
                     'tablename': tablename       // add the tablename to the GET parameters
                     },
                     success: function (data) { 
                         console.log(data)  // `data` is the return of the `loadcolumnNrules` view function
                        htmlappend += '<tr>';
                        htmlappend += data;
                        htmlappend += '</tr>';
                     $("#columntable").append(htmlappend);  // replace the contents of the column and dq rule input with the data that came from the server
                     }
                    });
                    
                });
        
        });

        $(document).on('click', '#removerow',function(){ 
            $(this).closest('tr').remove();
        }); // this is function to remove the table row

     
        $("#tables").change(function () {
            var url = $("#tables").attr("data-colrule-url");  // get the url of the `loadcolumnNrules` view
            var connectionId = $("#id_connections").val();  // get the selected connection ID from the HTML input
            var tablename = $(this).val(); // get the selected table from the HTML input
            
            if(tablename !='') {                 
                document.getElementById("qprofile").disabled=false;
              }; 
            
            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/ajax/loadcolumnNrules/)
                data: {
                'connectionid': connectionId, // add the connection id to the GET parameters
                'tablename': tablename       // add the table name to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `loadcolumnNrules` view function
                    console.log(data);
                $("#tablerow").html(data);  // replace the contents of the column and dq rule input with the data that came from the server
                }
            });
    
            });

            $(document).ready(function(){
                $(document).on('click','#qprofile', function(e){
                    e.preventDefault();
                    var connectionId = $("#id_connections").val();
                    var tablename = $("#tables").val();
                    var url = '/dqcharts/'+ connectionId + '|' + tablename;
                    
                    console.log(url)
                                       
                    window.open(url);

                                           
                    });
            
            });
            $(document).ready(function() {
                // messages timeout for 10 sec 
                $(".message").show().delay(6000).fadeOut(1000);
            });
    </script>
</div>
    


{% endblock %}

app/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        /* The sidebar menu */
        .sidenav {
            height: 100%; /* Full-height: remove this if you want "auto" height */
            width: 160px; /* Set the width of the sidebar */
            position: fixed; /* Fixed Sidebar (stay in place on scroll) */
            z-index: 1; /* Stay on top */
            top: 0; /* Stay at the top */
            left: 0;
            background-color: #111; /* Black */
            overflow-x: hidden; /* Disable horizontal scroll */
            padding-top: 20px;
        }

        /* The navigation menu links */
        .sidenav a {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 15px;
            color: #818181;
            display: block;
        }

        /* When you mouse over the navigation links, change their color */
        .sidenav a:hover {
            color: #f1f1f1;
        }

        /* Style page content */
        .main {
            margin-left: 160px; /* Same as the width of the sidebar */
            padding: 0px 10px;
            font-size: 80px;
            color: #818181;
        }

        .content {
            margin-left: 160px; /* Same as the width of the sidebar */
            padding: 0px 10px;
            font-size: 20px;
            color: #818181;
        }

        /* On smaller screens, where height is less than 450px, change the style of the sidebar (less padding and a smaller font size) */
        @media screen and (max-height: 450px) {
            .sidenav {padding-top: 15px;}
            .sidenav a {font-size: 18px;}
        }

        td, th {
            border: 1px solid #999;
            padding: 0.5rem;
        }

        .user {
            position: absolute;
            right: 50px;
            top: 30px;
            font-size: 20px;
          }   
          .pic {
            position: absolute;
            right: 50px;
            bottom: 30px;
          } 


</style>
    <title>Data Quality</title>
</head>
<body>
    <div class="pic">
        <img src="{% static 'images/VQD_logo_center_indigo_RGB.png' %}" width="250" height="150" >   
    </div> 
    <!-- Side navigation -->
<div class="sidenav">
    <a href="/">Home</a>
    {% if user.is_authenticated %}
        <a href="/newconnection/">Add Connection</a>
        <a href="/newdqcheck/">Add DQ Checks</a>
        <a href="/rundqcheck/">Run DQ Checks</a>
        <a href="/fileupload/" class="nav-link">File-Upload</a>
        <a href="/accounts/logout">Logout</a>
    {% else %}
        <a href="/accounts/login">Login</a>
    {% endif %}
  </div>

  <div class="user">
    {% if user.is_authenticated %}
    <a>Hello, {{user.username|capfirst}}</a>
    {% endif %}
  </div>
  
  {% block content %}

  {% endblock %}
   
     
</body>
</html>

app/templates/charts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>

            div
            {
                display: block;
                position: relative;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
            }
            
            .chart
            {
                width: 100%;
                background: #FFFFFF;
                padding-top: 10px;
                padding-bottom: 116px;
            }
          
            .chart_row
            {
                margin-top: 20px;
            }
            
            
            .chart_container
            {
                width: calc(100% + 30px);
                left: -px;
            }
            .chart
            {
                width: calc(100% / 2);
                padding-left: 15px;
                padding-right: 15px;
                margin-bottom: 58px;
            }
            .chart_content
            {
            
            }
            .chart_image
            {
                width: 100%;
            }
           
            
    </style>
    <title>DQ Report</title>
</head>
<body>
    
    <div class="chart" id="chart">
		<div class="container">
            
			
			<div class="row chart_row">
				<div class="col">
					<div class="chart_container item_grid">

                        <!-- Destination -->
                        
						<div class="chart item">
							<div class="chart_image">
								<canvas id="myChartnullchk" width="100" height="100"></canvas>
							</div>
							
                        </div>
                        
                        <div class="chart item">
							<div class="chart_image">
								<canvas id="myChartvalidvalues" width="100" height="100"></canvas>
							</div>
							
						</div>

						<div class="chart item">
							<div class="chart_image">
								<canvas id="myChartpatterncheck" width="100" height="100"></canvas>
							</div>
                        </div>
					</div>
				</div>
			</div>
		</div>
	</div>
    


    
    <script src="https://code.jquery.com/jquery-3.4.0.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"script></script>
    
    <script>
    
        $(document).ready(function(){
            var runbatchid = parseInt("{{ id }}")
            var url = '/dqcharts/api/chartsdata/'

            $.ajax({                       // initialize an AJAX request
                url: url,                    // set the url of the request (= localhost:8000/ajax/loadbatchrun/)
                data: {
                'runbatchid': runbatchid // add the connection id to the GET parameters
                },
                success: function (data) {   // `data` is the return of the `loadbatchrun` view function
                    
                    console.log(data);
                    console.log(data.labels)
                    var nullcheckdata=data.Null_Check;
                    var validvaluedata=data.Valid_Values;
                    var patterncheckdata=data.Pattern_Check;

                    if (nullcheckdata.totalcount != 0) {
                        var ctx = document.getElementById('myChartnullchk');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels:nullcheckdata.labels,
                                datasets: [{
                                    label: nullcheckdata.DqruleName,
                                    data: nullcheckdata.measuredcount,
                                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                                    borderColor: 'rgb(255, 99, 132)',
                                    borderWidth:1,
                                    barThickness: 80,
                                    
                                }]
                            
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            min: 0,
                                            max: nullcheckdata.totalcount,
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    }

                    if (validvaluedata.totalcount != 0) {
                        var ctx = document.getElementById('myChartvalidvalues');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels:validvaluedata.labels,
                                datasets: [{
                                    label: validvaluedata.DqruleName,
                                    data: validvaluedata.measuredcount,
                                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                                    borderColor: 'rgb(255, 99, 132)',
                                    borderWidth:1,
                                    barThickness: 80,
                                    
                                }]
                            
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            min: 0,
                                            max: validvaluedata.totalcount,
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    }
                    
                    if (patterncheckdata.totalcount != 0) {
                        var ctx = document.getElementById('myChartpatterncheck');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels:patterncheckdata.labels,
                                datasets: [{
                                    label: patterncheckdata.DqruleName,
                                    data: patterncheckdata.measuredcount,
                                    backgroundColor: 'rgba(255, 99, 132, 0.2)',
                                    borderColor: 'rgb(255, 99, 132)',
                                    borderWidth:1,
                                    barThickness: 80,

                                }]

                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            min: 0,
                                            max: patterncheckdata.totalcount,
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    }

                //$("#runbatch").html(data);  // replace the contents of the column and dq rule input with the data that came from the server
                }
            });
        });
        

    </script>

</body>
</html>

app/templates/dqcheckupload.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
<form  method="POST" enctype="multipart/form-data" id="fileForm">

  {% csrf_token %}

  <label for="dqcheckfile">
    <strong>Upload the DQ check file</strong>
  </label>
  <br><br>
  <input type="file" id="dqcheckfile" name="dqcheckfile">
  <br><br>

  <label for="delimiter">Field Separator : </label>
  <select name="delimiter" id="delimiter">
    <option value="comma">Comma</option>
    <option value="pipe">Pipe</option>
    <option value="tab">Tab</option>
  </select>

  <br><br>

  <label for="filehead">First Line Column Names : </label>
  <input type="checkbox" id="filehead" name="filehead" checked>
  

  <br><br>

  <label for="filetrail">File Has Trailer : </label>
  <input type="checkbox" id="filetrail" name="filetrail">
  

  <br><br>
  
  <input type="button" id="fileprofile" value="Run Profile" >

 

<br><br>
    {% for message in messages %}
        {{ message }}
    {% endfor %}

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

var token = '{{csrf_token}}';


  $(document).ready(function(){
    $(document).on('click','#fileprofile', function(e){
        e.preventDefault();
        var data = new FormData();
        var file = $('#dqcheckfile')[0].files[0]
        var dlimiter = $('#delimiter').val()
        var head = $('#filehead').val()
        var trail = $('#filetrail').val()

        data.append("file", file);
        data.append("delimiter", dlimiter);
        data.append("filehead", head);
        data.append("filetrail", trail);

        console.log(data)

        var url = '/runfileprofile/';
        $.ajax({
          url: url,
          type: 'POST',
          headers: { "X-CSRFToken": token },
          data: data,
          enctype: 'multipart/form-data',
          contentType: false,
          processData: false,
          success: function (data) {
            console.log(data);
            var newwindow = window.open("", "new window", "width=200, height=100");
            newwindow.document.write(data)
                          }
      
      });

                               
    });

});


</script>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
  <!-- Page content -->
  <div class="main">
    <h2> Welcome To Data Quality Framework </h2>
    <br>
    <p>Select from left Menu </p>
  </div>
   
  {% endblock %}

app/templates/loadColumnsAndDqRules.html
<td> <select name="column" id="column"> 
    <option value="">---------</option> 
    {% for column in columnlist %} 
    <option value="{{ column }}">{{ column }}</option> 
    {% endfor %} 
</select>
</td>

<td> <select name="dqrule" id="dqrule"> 
    <option value="">---------</option> 
    {% for dqrule in dqrulelist %} 
    <option value="{{ dqrule }}">{{ dqrule }}</option> 
    {% endfor %} 
</select>
</td>

<td> <input type="text" name="optvalues" id="optvalues"> </td>
<td><button type="button" id="removerow"></button></td>

app/templates/loadbatchrun.html
{% for batchrun in batchrunlist %}
<tr>
    <td> {{ batchrun.runstarttime }} </td>
    

    <td> {{ batchrun.runendtime }} </td>
    

    <td > {{ batchrun.runstatus }} </td>

    {% if batchrun.runstatus == "Completed" %}
    
        <td><a href="/dqcharts/{{ batchrun.id }}" id="dqreport" data-id="{{ batchrun.id }}">View Report</a></button></td>

    {% elif batchrun.runstatus == "Running"  %}

        <td><a href="" id="dqrunrefresh" data-id="{{ batchrun.id }}">Refresh</a></button></td>

    {% else  %}

        <td><a href="" id="dqrunerrorreport" data-id="{{ batchrun.id }}">Error</a></button></td>
        
    {% endif %}

</tr>

{% endfor %}

app/templates/loadtableslist.html
<option value="">---------</option>
{% for table in tablelist %}
<option value="{{ table }}">{{ table }}</option>
{% endfor %}

app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
   <form action="login" method="POST">
    {% csrf_token %}
    <h1>DataQuality Login</h1>
    <label for="username">Username</label>
    <input type="text" name="username"><br><br>
    <label for="password">Password</label>
    <input type="password" name="password"><br>
    <br>
    <br>
    <button name="name" value="value" type="submit">Login</button>
   </form> 

   {% for message in messages %}
   {{ message }}
   {% endfor %}
</div>   



{% endblock %}

app/templates/newconnection.html
{% extends 'base.html' %}

{% block content %}

<div class="content">

  <form action="addconnection" method="POST" id="newconnection" data-form-url="{% url 'loadform' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <h1>Create New Connection</h1>
    
    <!-- {{ form.as_p }} -->

    <label for="id_connections">Select Database :</label>

      <select id="id_connections" name="id_connections"  required>
        <option value="" disabled="true" selected>-- Select --</option>
        {% for connection in dblist %}
        <option value="{{ connection.id }}">{{ connection.dbname }}</option>
        {% endfor %} 
    </select>
 
 <br><br>   
 <table name="forms"  id="forms"></table>
 <div name="connectionstatus"  id="connectionstatus" ></div>

 
 {% for message in messages %}
 <div class="message">
  <pre>{{ message|wordwrap:80 }}</pre>
</div>
 {% endfor %}

  <input type="submit" name="connection" value="Add Connection">
  <input type="button" id="testconnection" name="connection" value="Test Connection">
  

<br><br>

</form>


 <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_connections").change(function () {
        var url = $("#newconnection").attr("data-form-url"); 
        var selecteddb = $("#id_connections").val(); 
        $.ajax({                  // initialize an AJAX request
          url: url,                    // set the url of the request (= localhost:8000/hr/ajax/loadtables/)
          data: {
          'selecteddb': selecteddb       // add the connection id to the GET parameters
          },
          success: function (data) {   // `data` is the return of the `loadtables` view function
              console.log(data);
              $("#forms").html(data);// replace the contents of the table input with the data that came from the server
          }
      });
        });

        $('#testconnection').on('click',function () {
          var url = '/ajax/load-form/';
          var selecteddb = $("#id_connections").val();
          var connection = $("#testconnection").val();
          var dbname = $('input[name=dbname]').val();
          var schemaname = $('input[name=schemaname]').val();
          var username = $('input[name=username]').val();
          var password = $('input[name=password]').val();
          var hostname = $('input[name=hostname]').val();
          var port = $('input[name=port]').val();
          $.ajax({  
            url: url,
            data: {
            'selecteddb': selecteddb,
            'connection': connection,
            'dbname' :dbname,
            'schemaname' :schemaname,
            'username':username,
            'password':password,
            'hostname':hostname,
            'port':port,
            },
            
            success: function (data) {   
               // console.log(data);
                $("#connectionstatus").html(data);
               $("#connectionstatus").show().delay(6000).fadeOut(1000);
            }
        });
          });
          $(document).ready(function() {
            // messages timeout for 10 sec 
            $(".message").show().delay(6000).fadeOut(1000);
        });
  </script>

</div>   
    
{% endblock %}

app/templates/newform.html
        
        {{ form.as_table}}

app/templates/uploadfile.html
{% extends 'base.html' %}

{% block content %}

<div class="content">
<form  method="POST" enctype="multipart/form-data" id="fileForm">

  {% csrf_token %}

  <label for="dqcheckfile">
    <strong>Upload the DQ check file</strong>
  </label>
  <br><br>
  <input type="file" id="dqcheckfile" name="dqcheckfile">
  <br><br>

  <label for="delimiter">Field Separator : </label>
  <select name="delimiter" id="delimiter">
    <option value="comma">Comma</option>
    <option value="pipe">Pipe</option>
    <option value="tab">Tab</option>
  </select>

  <br><br>

  <label for="filehead">First Line Column Names : </label>
  <input type="checkbox" id="filehead" name="filehead" checked>
  

  <br><br>

  <label for="filetrail">File Has Trailer : </label>
  <input type="checkbox" id="filetrail" name="filetrail">
  

  <br><br>
  
  <input type="submit" value="Run Profile" >



<br><br>
    {% for message in messages %}
        {{ message }}
    {% endfor %}

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>

  var token = '{{csrf_token}}';

  $(document).ready(function(){
    $(document).on('submit','#fileForm', function(e){
      e.preventDefault();

      $form = $(this)
      var formData = new FormData(this);

      console.log(formData)

      var url = '/runfileprofile/';
                
      $.ajax({   
        type: "POST",
        //csrfmiddlewaretoken: '{{ csrf_token }}',
        headers: { "X-CSRFToken": token },
        url: url,                    
        data: formData,
        contentType: false,
        processData: false,
        success: function (data) {   
          window.open(data)
          
        }
    });
                               
    });

});
</script>
</div>
{% endblock %}